/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // Cohere Design System Colors
        primary: "#17171c",
        "cohere-black": "#000000",
        ink: "#212121",
        "deep-green": "#003c33",
        "dark-navy": "#071829",
        canvas: "#ffffff",
        "soft-stone": "#eeece7",
        "pale-green": "#edfce9",
        "pale-blue": "#f1f5ff",
        hairline: "#d9d9dd",
        "border-light": "#e5e7eb",
        "card-border": "#f2f2f2",
        muted: "#93939f",
        slate: "#75758a",
        "body-muted": "#616161",
        "action-blue": "#1863dc",
        "focus-blue": "#4c6ee6",
        coral: "#ff7759",
        "coral-soft": "#ffad9b",
        "form-focus": "#9b60aa",
        "on-primary": "#ffffff",
        "on-dark": "#ffffff",
        error: "#b30000",
        // Legacy aliases for compatibility
        background: "#ffffff",
        surface: "#ffffff",
        textPrimary: "#212121",
        textSecondary: "#93939f",
        success: "#059669",
        warning: "#D97706",
      },
      borderRadius: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "22px",
        xl: "30px",
        pill: "32px",
      },
      fontSize: {
        "hero-display": ["96px", { lineHeight: "1", letterSpacing: "-1.92px" }],
        "product-display": ["72px", { lineHeight: "1", letterSpacing: "-1.44px" }],
        "section-display": ["60px", { lineHeight: "1", letterSpacing: "-1.2px" }],
        "section-heading": ["48px", { lineHeight: "1.2", letterSpacing: "-0.48px" }],
        "card-heading": ["32px", { lineHeight: "1.2", letterSpacing: "-0.32px" }],
        "feature-heading": ["24px", { lineHeight: "1.3", letterSpacing: "0" }],
        "body-large": ["18px", { lineHeight: "1.4", letterSpacing: "0" }],
        body: ["16px", { lineHeight: "1.5", letterSpacing: "0" }],
        button: ["14px", { lineHeight: "1.71", letterSpacing: "0" }],
        caption: ["14px", { lineHeight: "1.4", letterSpacing: "0" }],
        micro: ["12px", { lineHeight: "1.4", letterSpacing: "0" }],
      },
      spacing: {
        xxs: "2px",
        xs: "6px",
        section: "80px",
      },
    },
  },
  plugins: [],
};
